export enum SortOption {
    PRICE_LOW_TO_HIGH = 'PRICE_LOW_TO_HIGH',
    PRICE_HIGH_TO_LOW = 'PRICE_HIGH_TO_LOW',
    RATING_HIGH_TO_LOW = 'RATING_HIGH_TO_LOW',
    CAPACITY_HIGH_TO_LOW = 'CAPACITY_HIGH_TO_LOW',
    ROOM_SIZE_LARGE_TO_SMALL = 'ROOM_SIZE_LARGE_TO_SMALL'
}