name: Deploy IaC
on:
  push:
    branches:
      - dev
    paths:
      - 'iac/**'
      - '.github/workflows/deploy-iac.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    env:
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_project_name: ${{ vars.PROJECT_NAME }}
      TF_VAR_team_name: ${{ vars.TEAM_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.config
        working-directory: ./iac
#
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./iac
#
      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./iac

      - name: Set Repository Variables
        run: |
          DISTRIBUTION_ID=$(terraform output -raw cloudfront_distribution_id || echo "")
          BUCKET_NAME=$(terraform output -raw frontend_bucket_name || echo "")

          # Using GitHub API directly
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables/CLOUDFRONT_DISTRIBUTION_ID" \
            -d "{\"value\":\"$DISTRIBUTION_ID\"}"

          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/variables/FRONTEND_BUCKET_NAME" \
            -d "{\"value\":\"$BUCKET_NAME\"}"
        working-directory: ./iac

permissions:
  contents: read
  actions: write